GET http://localhost:5000/users
###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name":"herman",
    "nohp":"6285693095506"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "nohp":"6282371579665"
}

###
GET http://localhost:5000/otp
Content-Type: application/json

{
    "nohp":"6282371579665"
}
###
POST  http://localhost:5000/verifyotp
Content-Type: application/json

{
    "nohp":"6282371579665",
    "code":"731543"
}

###
GET http://localhost:5000/token

###
GET http://localhost:5000/refreshtoken

###
DELETE http://localhost:5000/logout

###
POST http://localhost:5000/send-otp
Content-Type: application/json

{
    "nohp":"6282371579665",
    "msg":"testtt"
}

